apiVersion: extensions/v1beta1
kind: Deployment                                          # 资源类型
metadata:
  name: redis-deployment
spec:
  replicas: 1                                             # pod 副本数量
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 部署策略 滚动升级
    rollingUpdate: 
      maxUnavailable: 1                                   # 在升级过程中最多允许几个 pod 不可用
      maxSurge: 1                                         # 升级过程中允许最多添加几个 pod, 如果 副本是 2 升级过程中要保证可用一直是 2 必须要再加一个 pod
  template:                                               # 定义 deploy 使用 pod
    metadata:
      labels:
        app: redis                                  #  模板定的 pod 的 label 根据这个 label 生成 service
    spec:                                               # spec 相当于 step-one 中的 pod
      containers:
        - image: redis:5.0.4
          imagePullPolicy: Always                         # 镜像策略
          name: redis
          ports:
            - containerPort: 6379                         # 一种显示的定义 和 dockerfile 中的 expose 相同